run:
  timeout: 5m

linters-settings:
  gci:
    custom-order: true
    sections:
    - standard
    - default
    - prefix(github.com/go-kratos/kratos-layout)
    - blank
    - dot
  gofmt:
    simplify: true
    rewrite-rules:
    - pattern: 'interface{}'
      replacement: 'any'

linters:
  enable:
  - gci
  - gofmt
