[server.http]
addr = "0.0.0.0:8000"
timeout = "1s"

[server.grpc]
addr = "0.0.0.0:9000"
timeout = "1s"

[server.profile]
enabled = true
addr = "0.0.0.0:6060"
timeout = "1s"

[data.database]
driver = "mysql"
source = "root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local"

[data.redis]
addr = "127.0.0.1:6379"
read_timeout = "0.2s"
write_timeout = "0.2s"